# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ReplaceDirectionWindow.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ColumnReplace(object):
    def setupUi(self, ColumnReplace):
        ColumnReplace.setObjectName("ColumnReplace")
        ColumnReplace.resize(640, 500)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(ColumnReplace)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.SelectInput = QtWidgets.QPushButton(ColumnReplace)
        self.SelectInput.setObjectName("SelectInput")
        self.horizontalLayout_2.addWidget(self.SelectInput)
        self.InputFilePath = QtWidgets.QLineEdit(ColumnReplace)
        self.InputFilePath.setObjectName("InputFilePath")
        self.horizontalLayout_2.addWidget(self.InputFilePath)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.SelectOutput = QtWidgets.QPushButton(ColumnReplace)
        self.SelectOutput.setObjectName("SelectOutput")
        self.horizontalLayout_3.addWidget(self.SelectOutput)
        self.OutputFilePath = QtWidgets.QLineEdit(ColumnReplace)
        self.OutputFilePath.setText("")
        self.OutputFilePath.setObjectName("OutputFilePath")
        self.horizontalLayout_3.addWidget(self.OutputFilePath)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2.addLayout(self.verticalLayout_4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(ColumnReplace)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.TargetCombo = QtWidgets.QComboBox(ColumnReplace)
        self.TargetCombo.setObjectName("TargetCombo")
        self.verticalLayout.addWidget(self.TargetCombo)
        self.label_2 = QtWidgets.QLabel(ColumnReplace)
        self.label_2.setTextFormat(QtCore.Qt.AutoText)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.BackupCombo = QtWidgets.QComboBox(ColumnReplace)
        self.BackupCombo.setObjectName("BackupCombo")
        self.verticalLayout.addWidget(self.BackupCombo)
        self.line = QtWidgets.QFrame(ColumnReplace)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.ReplaceBtn = QtWidgets.QPushButton(ColumnReplace)
        self.ReplaceBtn.setDefault(False)
        self.ReplaceBtn.setObjectName("ReplaceBtn")
        self.verticalLayout.addWidget(self.ReplaceBtn)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.DataPreview = QtWidgets.QTableWidget(ColumnReplace)
        self.DataPreview.setObjectName("DataPreview")
        self.DataPreview.setColumnCount(0)
        self.DataPreview.setRowCount(0)
        self.horizontalLayout.addWidget(self.DataPreview)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.ExitButton = QtWidgets.QPushButton(ColumnReplace)
        self.ExitButton.setObjectName("ExitButton")
        self.horizontalLayout_6.addWidget(self.ExitButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)

        self.retranslateUi(ColumnReplace)
        self.ExitButton.clicked.connect(ColumnReplace.close)
        QtCore.QMetaObject.connectSlotsByName(ColumnReplace)

    def retranslateUi(self, ColumnReplace):
        _translate = QtCore.QCoreApplication.translate
        ColumnReplace.setWindowTitle(_translate("ColumnReplace", "ColumnReplace"))
        self.SelectInput.setText(_translate("ColumnReplace", "Select Input File "))
        self.SelectOutput.setText(_translate("ColumnReplace", "Select Output File"))
        self.label.setText(_translate("ColumnReplace", "Select High Alt Column"))
        self.label_2.setText(_translate("ColumnReplace", "Select Low Alt Column"))
        self.ReplaceBtn.setText(_translate("ColumnReplace", "Do It!"))
        self.ReplaceBtn.setShortcut(_translate("ColumnReplace", "Ctrl+S"))
        self.ExitButton.setText(_translate("ColumnReplace", "Exit"))

